sudo: required
language: java
jdk: oraclejdk11

services:
  - docker

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  sonarcloud:
    organization: mikhailzheltyshev
    token:
      secure: "VB5LEPtULU++a1Cl0sQ8u22WLyK4QIqYtlDcmTCbW42P2DVcHwGTbZE7Xdi1c3XDUfhW6Bx0XSB019tu+lHSia94w01H+CpLy88ua90gI9jSy/eNu5dB2EQgpQKi
               jrzAjnI+aG+SugAUEtvbKPt2I0b7Vj7kjDdq/8CasbpbUlWDZm19LugK4fEvhumyN+G8oZlx+p4rLoTh5PI/NADNTkv322Hg/8hqk24x00Z0XuJgoof/z+BI57Xy+TGUvyDaP6u
               Xwtw7ewLLi3urkZCXehoSfZKfu5as/MS6MKhfpU0myN/8hSj6Px1SEx8mj9q8oQL6UwK2ePpQYFWqcC3EU8aSMppIUyXGDA/mVTSBYTXH6dc0/lBWcmzPQ3W2XbcT/wE4q10KEu
               T9Yzj1nZ64j90ZcLtE97Z0z2x7L7BdfviEQ0F+iv6fSUxZO2qSSORZpMjSWkDOXKhZmwwP+KM9wvcPucfZnB6w7Qfu6dPUlgN2rMdBYxs7QV2wnRihKj7l2rgvclcqRONHRkySQ
               b6ZHYjIwdx3SMo4OsMURxpegVyi04g8fJfcF625py4EmgAOpSkvrShjnQe2gIaF3SESqLG3YzNSEXB4bciu9+q88LLpt7VuF0D5adkiqC6UVKcKSShN3EMlTxCOPm2dhdLMlN4M
               TxlnPqll84VYXUx85Mg="

script:
  - ./gradlew clean check
  - ./gradlew jacocoTestReport sonarqube
  - ./gradlew bootJar

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH; fi`
  - export IMAGE_NAME=mihalichzh/ci-cd-spring-boot
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$TRAVIS_COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME