language: java
jdk: oraclejdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  sonarcloud:
    organization: mikhailzheltyshev
    token:
      secure: "YGm6J3mZ7NwwttwPa7hOtJFZnstbYExQl35AunuRWa/Wm2Csi7149Qkyp1xekglRW/DAZzNGeR47W4GL3VZ1v2fsPK6JiT3M2bVKw/VgqGoYiZfsu7g7kkfpvcFTmwiKj2VWYiIYkbEJPzjPG0YzD/Owh0u6DX2n8ByDxO+xEKNqXZylucJ3zgC9GMQrVzmbCeEs5e2o9/Ln1eBtdpvtQjeguVhHrxY+OabCSwBViXR9uwVmva72Eu6a0F0d6N0Tw1Upf4prKXYUSNZhvz5oN9pxnsImq6mZdkedesfCCG3rHV+Hj61K6XjxWd6uo4iGoyskTkOfpUJIrJseYWmt59lvsWzTVFsxdhQAvmxOe+uO5QSiz+2XW7hmBA/t9XFOZV+x9beNMZCYbGUOU7qfTiZl+5BaUqB14dS3S8fMYC7bnX09nGke5aX4RsVJ9toX8yVRyrGn8Lc2KrQUqLMadCK0IB/DpHbHvTvOOucD89Q4z4VzFb1u7OEcppIu/qXRQU757lVdPjucJojt3ygSdv1siPkzaWBQ0HOm1OWsA7EIJYnCc4L87R0TaCu0MLCs2gMUMXak0QJ4hZ8O21wjQV3WiTJmii3XO/bzF/tCcZOgWFfplyUGcrPjuB7Lcw/2AzqNr9P0ZLsqhNeSqVYWYWp+uvP8PZiUi2ipi1Vniq0="

script:
  - ./gradlew clean check
  - ./gradlew jacocoTestReport sonarqube