language: java
jdk: oraclejdk11

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
    - secure: "bNn+GyQhVqqKiM2DMNYFixxRSASFjDlwizqVlPO+OBUCHG2zYYN+NtTocT7/gmuRBMEB71wpCyfUpa4ZWmdxSqYQXQGg9P38YozUm2x3xYcC24oB4EL8WN44gbDQ
        EHftUVRSlQOJO02u+CgXqMJAUc8o1hrPSYDvBk7FBGDiTYo6mqeMJQPC12QGBUj3ezvP59hceJ3koDu8Lc56OTmcl7kEp2tH0/Fs1gUhBOy3+oaZIvatEnLe9TWDt03UTeBSEx5
        7JbQW1haWquGQWg7VjMIMBe9DEuVwXBEdttc4zBVzIzSOAwpFEqR3JwB4EdO4Jwn9Z31Ca+Gc8/FTxRhjnWGN+eQ3TrCFxnJYRY0GTl0LstEp34ZbZxTep16rT1V/+Dad5FmpaZ
        kXLQ3eZkSmiamTNkzfoJsa4jO5HUZZG085MkzAVGdktbZD/1uUFZ9rjxkpdo4j9P+dp5LxSxllYMSmrnBoOBwTwfIByMrXRwQkjf31xYNACQi8QQn2kNjnnNmzK52lkOR4eX6t8
        arg3fxwp3mNzgW5I/Eo0ntttuQpMXLtkCHurZyZTKYkpO8caI5JyDuqjajrSFJbA7uXoj60uHvBgrFaOrwL7K3CkulRe5abOnN2z+7NfScJ2KHACP9Z7b5b5u2Tu/Jgq+e4yzmX
        3oTL5nNCjMKwqSC7CK0="

addons:
  sonarcloud:
    organization: mikhailzheltyshev
    token:
      secure: $SONAR_TOKEN

script:
  - ./gradlew clean check
  - ./gradlew jacocoTestReport sonarqube